from http import HTTPStatus
from flask import jsonify, request

from .auth import validate_user_token
from utils.utils import validate_dataset_id


def get_sample_from_dataset():
    """
    Demo Endpoints for returning the randomly sampled data from the DApp backend,
    using the randomness generated by the algorand beacon
    """
    try:
        auth_header = request.headers.get('Authorization')
        if not auth_header:
            return (
                jsonify(
                    dict(status=False, message="No Auth Header specified. Please specify Authorization header"),
                ),
                HTTPStatus.UNAUTHORIZED,
            )

        if bearer_header := auth_header.split(" "):
            if bearer_header[0] != "Bearer":
                return (
                    jsonify(
                        dict(status=False, message="Authorization header should start with Bearer. Please use correct auth"),
                    ),
                    HTTPStatus.UNAUTHORIZED,
                )

        auth_token = bearer_header[1]
        (validated, decoded_token) = validate_user_token(auth_token)
        if not validated:
            return (
                jsonify(
                    dict(status=False, message="Invalidated Token. Please try again"),
                ),
                HTTPStatus.UNAUTHORIZED,
            )

        print("========== decoded token is: ", decoded_token)
        data = request.get_json()
        if not data.get("dataset_id"):
            return (
                jsonify(
                    dict(status=False, message="Please supply a dataset Id to use this API"),
                ),
                HTTPStatus.BAD_REQUEST,
            )
        if not validate_dataset_id(data.get("dataset_id")):
            return (
                jsonify(
                    dict(status=False, message="Invalid Dataset ID. Please use the correct one"),
                ),
                HTTPStatus.BAD_REQUEST,
            )


        return (
            jsonify(dict(status=True, message="All Good!", data=data)),
            HTTPStatus.OK,
        )
    except Exception as e:
        return (
            jsonify(
                dict(status=False, message=str(e))
            ),
            HTTPStatus.BAD_GATEWAY,
        )
